#!/usr/bin/env bash
pgrep ags | xargs kill 2>&1 >/dev/null
nix profile remove bens-ags
nix profile install .
hyprctl dispatch "exec bens-ags -b hypr &"
if [[ $1 == '-i' || $1 == '--inspect' ]]; then
  sleep 1
  bens-ags -b hypr -i
fi
